#default        
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: C:\upload\jeiglobal\hk\announcements
        
spring:
    resources:
        cache-period:31556926
        
serverurl:
     hongkong: http://localhost:8080
     globalbms: http://localhost:8081
     
---
spring.profiles: develop

#develop        
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: /home/devhk/upload/announcements
        
spring:
    resources:
        cache-period:31556926
        
serverurl:
     hongkong: http://devhk.jei-global.com
     globalbms: http://devbms.jei-global.com
     
---
spring.profiles: product

#product
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: /home/devhk/upload/announcements
        
spring:
    resources:
        cache-period:31556926