        
multipart:
    maxFileSize: 2048KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: C:\upload\jeiglobal\hk\announcements
        
spring:
    resources:
        cache-period:31556926
---
spring.profiles: develop
        
multipart:
    maxFileSize: 2048KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: /home/devhk/upload/announcements
        
spring:
    resources:
        cache-period:31556926
---
spring.profiles: product

multipart:
    maxFileSize: 2048KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: /home/devhk/upload/announcements
        
spring:
    resources:
        cache-period:31556926