#default        
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: C:\upload\jeiglobal\hk\announcements
        promotionitem : C:\workspace\HongKong\src\main\webapp\public\promotion\
        
serverurl:
     hongkong: http://localhost:8080
     globalbms: http://localhost:8081
     
cookieShare:
     domain: localhost
  
filePath:
     img: /public/img # 이미지 파일 경로
     js: /public/js   # js 파일 경로
     css: /public/css # css 파일 경로
     
flag:  
    fstVisit: 15   # 첫관리방문일 허용 기준일
    mgFstVisit: 7  # 마감날 첫관리방문일 허용 기준일
    studyNum: 1    # 관리횟수
    bookNum: 1     # 불출수
    feeMonthNum: 1 # 입금 등록 허용 기준 개월 수
    
page:
    blockSize: 10  # 한 블록에 출력될 페이지 개수
    size: 100      # 한 페이지에 출력될 레코드 개수 
---
spring.profiles: develop

#develop        
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: /home/devhk/upload/announcements
        promotionitem : /home/hk/webapps/ROOT/public/promotion
spring:
    resources:
        cache-period:31556926
        
serverurl:
     hongkong: http://devhk.jei-global.com
     globalbms: http://devbms.jei-global.com

cookieShare:
     domain: .jei-global.com
---
spring.profiles: product

#product
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: /home/devhk/upload/announcements
        promotionitem : /home/hk/webapps/ROOT/public/promotion
        
spring:
    resources:
        cache-period:31556926
        
cookieShare:
     domain: .jei-global.com